### PR TITLE
added linked_name option for the post body

### PR DESCRIPTION
**Pull request by pontusarfwedson**
PR to add functionality for the user to use `link_names` in slack notification. This gives the user possibility to ping user groups etc which otherwise is impossible.

### CODE REVIEW

**Comment by drnic** [comment]
Thanks!

**Comment by drnic** [comment]
@pontusarfwedson I merged this because it looked harmless at a glance; unfortunately it might have broken the CI pipeline. I've revert it on master. I'm sorry but can I ask you to create the PR again, and confirm that `docker build -t cfcommunity/slack-notification-resource .` runs ok first? Thanks!

**Comment by pontusarfwedson** [comment]
Hey! Yes, did a poor job with testing, will do that!
/Pontus

ons 21 mars 2018 kl. 03:41 skrev Dr Nic Williams <notifications@github.com>:

**Comment by pontusarfwedson** [comment]
Hey Dr Nic Williams!
I think the initial issue was that I actually forgot a comma in the build
of the json. So that made the json unparseable. However, when fixed that I
still have a hard time making the tests pass. Cannot really seem to figure
out how you've constructed the tests, doesn't seem to easy to adapt them.
Any input?

2018-03-21 3:31 GMT+01:00 Dr Nic Williams <notifications@github.com>:

**Pull request merged**
