### PR TITLE
support insecure connection to mattermost and custom ca-certificates

### PR DESCRIPTION
**Pull request by o-orand**

### CODE REVIEW

**Comment by o-orand** [comment]
Hi @drnic & @dennisjbell are you maintaining this resource or should I merge myself ? thanks !

**Comment by drnic** [comment]
Sorry mate. Yep I'm happy if you want to help maintain it, merge PRs and cut versions.
Perhaps the latter will require some bonus work to get docker images cut. Let me know how far you get.






On Fri, Oct 7, 2016 at 8:01 PM +1000, "Olivier Orand" <notifications@github.com> wrote:












Hi @drnic & @dennisjbell are you maintaining this resource or should I merge myself ? thanks !

**Comment by lnguyen** [comment]
Thanks!

**Comment by lnguyen** [comment]
Hey @o-orand I've pushed v1.0.1

**Pull request merged**
